### This script creates a template to serve as a prior for the 
### individualized network metrics generated by templateICA
###
### Ellyn Butler & Damon Pham
### April 17, 2024 - 


# Input directory
in_dir <- '/projects/b1108/studies/mwmh/data/processed/neuroimaging/'
#in_dir <- '~/Documents/Northwestern/studies/mwmh/data/processed/neuroimaging/surf/'

# Output directory
out_dir <- '/projects/b1108/studies/mwmh/data/processed/neuroimaging/template_Yeo17'
#out_dir <- '~/Documents/Northwestern/studies/mwmh/data/processed/neuroimaging/template_Yeo17'

# Packages
#devtools::install_github('mandymejia/fMRItools', '0.4') # Need dev version, not CRAN
library(fMRItools)
stopifnot(utils::packageVersion('fMRItools') >= '0.4.4')
#install.packages('ciftiTools')
library(ciftiTools)
ciftiTools.setOption('wb_path', '/Applications/workbench')
#devtools::install_github('mandymejia/templateICAr', '8.0') # Need dev version, not CRAN
#^ try again
library(templateICAr)
stopifnot(utils::packageVersion('templateICAr') >= '0.8.1')


## -----------------------------------------------------------------------------

###### Load and modify the Yeo 17 parcellation
GPARC <- ciftiTools::load_parc('Yeo_17')
### Get new labels by removing the subnetwork and LH/RH parts of the label.
y <- rownames(GPARC$meta$cifti$labels[[1]])
z <- gsub('17Networks_LH_|17Networks_RH_', '', y)
z <- gsub('_.*', '', z)
# ### Uncomment the below two lines if you want to keep left and right separate.
# y <- gsub('17Networks_', '', gsub('H_.*', 'H_', gsub('???', '', y)))
# z <- paste0(y, z)
### Apply new labels.
z <- factor(z, levels=z[!duplicated(z)])
GPARC <- convert_to_dlabel(
  newdata_xifti(GPARC, as.numeric(z)[c(as.matrix(GPARC))+1]),
  levels_old=as.numeric(z)[!duplicated(z)],
  levels=as.numeric(z)[!duplicated(z)] - 1,
  labels=levels(z),
  colors=rgb(
    GPARC$meta$cifti$labels[[1]]$Red,
    GPARC$meta$cifti$labels[[1]]$Green,
    GPARC$meta$cifti$labels[[1]]$Blue,
    GPARC$meta$cifti$labels[[1]]$Alpha
  )[!duplicated(z)],
  add_white=FALSE
)
GPARC$meta$cifti$labels[[1]] <- GPARC$meta$cifti$labels[[1]]
### Handle medial wall
GPARC$meta$cifti$labels[[1]] <- rbind(
  data.frame(Key=-1, Red=1, Green=1, Blue=1, Alpha=0, row.names='BOLD_mwall'),
  GPARC$meta$cifti$labels[[1]]
)
GPARC_2 <- as.matrix(GPARC)
xii1 <- read_cifti(cii_fnames$test[1], idx=1) * 0
BOLD_mwall <- c(do.call(c, xii1$meta$cortex$medial_wall_mask))
GPARC_2[!BOLD_mwall,] <- -1
GPARC <- newdata_xifti(GPARC, GPARC_2)
GPARC <- move_to_mwall(GPARC, values=-1)
#GPARC <- resample_xifti(GPARC, resamp_res=12000)
rm(q, y, z, GPARC_2, BOLD_mwall, xii1)

save(list=ls(), file=paste0(out_dir, 'template_Yeo17_HCP_args.rda'))

sample <- with(set.seed(0), sample(seq(length(cii_fnames$test)), 200))

temp_subjs <- read.csv(paste0(in_dir, 'tablulated/template_subjs.csv'))

cii_fnames <- c()
for (i in 1:nrow(temp_subjs)) {
  subid <- temp_subjs[i, 'subid']
  sesid <- temp_subjs[i, 'sesid']
  cii_fnames <- c(cii_fnames, paste0(in_dir, 'surf/sub-', subid, '/ses-', 
                  sesid, '/func/sub-', sesid, '/sub-', subid, '_ses-', sesid, 
                  '_task-rest_space-fsLR_desc-postproc_bold.dscalar.nii'))
}

temp <- estimate_template(
  cii_fnames, 
  GPARC,
  TR = .555, 
  brainstructures = c('left', 'right'),
  #resamp_res=12000,
  FC = FALSE,
  scale_sm_surfL = load_surf('left'),
  scale_sm_surfR = load_surf('right')#, usePar=4, wb_path=wb_path
)

saveRDS(temp, paste0(out_dir, 'temp.rds'))
