### This script creates a template to serve as a prior for the 
### individualized network metrics generated by templateICA
###
### Ellyn Butler & Damon Pham
### June 7, 2024

library(dplyr)

# Input directory
indir <- '/projects/b1108/studies/mwmh/data/processed/neuroimaging/'
#indir <- '~/Documents/Northwestern/studies/mwmh/data/processed/neuroimaging/'

# Output directory
outdir <- '/projects/b1108/studies/mwmh/data/processed/neuroimaging/template/'
#outdir <- '~/Documents/Northwestern/studies/mwmh/data/processed/neuroimaging/template/'

# HCP directory
hcp_dir <- '/projects/b1108/templates/HCP_S1200_GroupAvg_v1/'
#hcp_dir <- '~/Documents/Northwestern/templates/HCP_S1200_GroupAvg_v1/'

# Packages
#devtools::install_github('mandymejia/fMRItools', '0.4') # Need dev version, not CRAN
library(fMRItools)
stopifnot(utils::packageVersion('fMRItools') >= '0.4.4')
#install.packages('ciftiTools')
library(ciftiTools)
ciftiTools.setOption('wb_path', '/projects/b1108/software/workbench')
#devtools::install_github('mandymejia/templateICAr', '8.0') # Need dev version, not CRAN
#^ try again
library(templateICAr)
stopifnot(utils::packageVersion('templateICAr') >= '0.8.5')


## -----------------------------------------------------------------------------


save(list=ls(), file=paste0(outdir, 'template_Yeo17_MWMH_sub-all_ses-2_task-all_args.rda'))

temp_subjs <- read.csv(paste0(indir, 'tabulated/temp_subjs_sub-all_ses-2_task-all.csv'))

Sys.setenv('R_MAX_VSIZE'=32000000000)
for (j in 1:nrow(temp_subjs)) { 
  subid <- temp_subjs[j, 'subid']
  sesid <- temp_subjs[j, 'sesid']
  path <- c(system(paste0('find ', indir, 'surf/sub-', subid, '/ses-', 
            sesid, '/func/ ', '-name "*_space-fsLR_desc-postproc_smoothed.dscalar.nii"'), intern=TRUE))

  cii <- read_cifti(path)
  assign(paste0('cii', j), cii)
}

temp <- estimate_template(
  mget(paste0('cii', 1:nrow(temp_subjs))),
  GICA = GPARC,
  hpf = 0, 
  brainstructures = c('left', 'right'),
  resample_res = ,
  FC = FALSE,
  scale_sm_surfL = load_surf('left'),
  scale_sm_surfR = load_surf('right'), 
  verbose = TRUE#, usePar=4, wb_path=wb_path
) 

saveRDS(temp, paste0(outdir, 'temp_sub-all_ses-2_task-all.rds'))
